### ISSUE TITLE
音乐播放的node跑的接口是否有问题呢

### ISSUE THREAD

**Issue by dearwangzhe** [orbem/vue-music-webapp#21]
你的接口是music/url?id=33894312，我这本地跑的是node用song//url?id=33894312才可以呢。
还有你的项目和我的项目都报这个错：
    Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
这是什么原因呢

**Comment by tjh19971228** [comment]
谢谢大哥，提出de这个问题，我特意去看了下api文档，应该是api改了规则，因为我看到api文档里面的截图还是music的，但文档里已经改为了song
